### ISSUE TITLE
There are tedious windows and player can move outside the border

### ISSUE THREAD

**Issue by saiumr** [VisualGMQ/1MGame2022#1]
+ 在发布的[v0.1.0](https://github.com/VisualGMQ/1MGame2022/releases/tag/v0.1.0)版本中，双击打开游戏主体程序仍然会有命令行窗口
+ 玩家可以移动到边界外，但是在边界外子弹不会生成（或者不会从窗口边界外射到窗口内）
+ 在当前版本可以将怪物的移动速度和生成速度减小

**Comment by saiumr** [comment]
> * 在发布的[v0.1.0](https://github.com/VisualGMQ/1MGame2022/releases/tag/v0.1.0)版本中，双击打开游戏主体程序仍然会有命令行窗口
> * 玩家可以移动到边界外，但是在边界外子弹不会生成（或者不会从窗口边界外射到窗口内）
> * 在当前版本可以将怪物的移动速度和生成速度减小

对于第三点，另一个好一点的方法是将怪物的血量减少或者玩家伤害增大

**Comment by VisualGMQ** [comment]
咱就是说下次都可以用中文。
命令行的问题最后再说。
玩家移动到版外的情况已经修复了。
怪物移动速度和生成速度后面再调整。
